apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
    spec:
      containers:
        - image: lajcik007/udagram-reverse-proxy
          name: udagram-reverse-proxy
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080