apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user-app
  labels:
    app: udagram-api-user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user-app
  template:
    metadata:
      labels:
        app: udagram-api-user-app
    spec:
      containers:
        - name: udagram-api-user
          image: lajcik007/udagram-api-user
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"