apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user-app
  labels:
    app: udagram-api-user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user-app
  template:
    metadata:
      labels:
        app: udagram-api-user-app
    spec:
      containers:
        - name: udagram-api-user
          image: lajcik007/udagram-api-user
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
          env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: URL
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: JWT_SECRET
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: AWS_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: AWS_PROFILE
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: AWS_REGION
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: POSTGRES_USERNAME
          - name: POSTGRESS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: POSTGRESS_PASSWORD
          - name: POSTGRESS_DB
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: POSTGRESS_DB
          - name: POSTGRESS_HOST
            valueFrom:
              configMapKeyRef:
                name: config-env
                key: POSTGRESS_HOST